version: '3.7'

networks: 
  tmdgolangexample:

services:

  tmdgolangexample:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB1_POSTGRES_HOST=tmdgolangexample-db1"
      - "DB1_POSTGRES_PORT=5432"
      - "DB1_POSTGRES_SSL_MODE=prefer"
      - "DB1_POSTGRES_DB=tmdgolangexample"
      - "DB1_POSTGRES_USER=postgres"
      - "DB1_POSTGRES_PASSWORD=KNAbj6ErG537M7qb"
    volumes: 
      - ./:/go/src/github.com/thiagomotadev/tmdgolangexample
    networks: 
      - tmdgolangexample
    ports:
      - 8080:80

  tmdgolangexample-db1:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=KNAbj6ErG537M7qb"
    volumes: 
      - ./sql/db1:/docker-entrypoint-initdb.d
      - ./data/db1:/var/lib/postgresql/data
    networks: 
      - tmdgolangexample
